# Soloist Connect source: soloist:connect -> content type "sol".
#
#ID     Suffix          Mime Content-Type               Server File Type
sol     soloist:        ?                               audio
